### ISSUE TITLE
Can't build server

### ISSUE THREAD

**Issue by thomas-huet** [RoganMurley/Ring-of-Worlds#3]
`stack image container` doesn't work with the latest version of stack.

**Comment by RoganMurley** [comment]
Looks like we need to [switch to Docker multi-stage builds](https://www.fpcomplete.com/blog/2017/12/building-haskell-apps-with-docker). In the meantime here are some [instructions for installing an older version of Stack](https://roganmurley.com/2019/06/17/using-older-versions-of-stack.html), though I appreciate that might not be possible and is definitely not a long term solution.

**Comment by RoganMurley** [comment]
@thomas-huet I've pushed a first pass at a multi-stage docker build to the branch `multistage-docker-build`. The first compilation takes a while but it speeds up once the dependency layer is cached. You should be able to build the server with `docker-compose build`, and run it with `docker-compose up`.

**Comment by thomas-huet** [comment]
The multistage docker build now works however it's still impossible to run the code. The whole thing assumes that I want to deploy to `www.ringofworlds.com`:
- I need SSL certificates but I can't use them because they are encrypted (which makes sense but there is no alternative that I can use).
- The Nginx conf only accepts connections to `www.ringofworlds.com` (or redirects to it which is even worse because you may think you are testing your dev version but you're actually using the prod one).

**Comment by RoganMurley** [comment]
@thomas-huet Ah, sorry for the trouble. The multi-stage docker builds are now on `master`, and I've also just pushed `scripts/makeFakeCertificates` based on [this article](https://letsencrypt.org/docs/certificates-for-localhost/). If you run `./scripts/makeFakeCertificates && docker-compose build && docker-compose up` then accept the insecure certificate things should work 🤞 

The redirect thing is weird, what are the exact steps to reproduce?

**Comment by thomas-huet** [comment]
Everything seems to work fine now, the redirect happens if you go to http://localhost:8000/

**Comment by RoganMurley** [comment]
Great, let me know if you have any other problems! I'll look into the 8000 redirect issue but it's not a priority right now.
