### ISSUE TITLE
Remember when sound is turned off

### ISSUE THREAD

**Issue by thomas-huet** [RoganMurley/Ring-of-Worlds#7]
It is quite annoying that the sound is reset to maximum volume every time I click a link (every that's not "Play Again").

**Comment by RoganMurley** [comment]
I just [pushed a fix](https://github.com/RoganMurley/Ring-of-Worlds/commit/c8d075136bc4bdabc6bb26f77b664e9edc99a42d) for this, I'll deploy it tomorrow!

**Comment by thomas-huet** [comment]
The fix doesn't work. The volume is stored correctly (the slider in the setting is where I last put it) but the stored volume is ignored on startup.

**Comment by RoganMurley** [comment]
Oops, I probably should have tested with audio on rather than relying on the slider. Should be good now 🤞
