### ISSUE TITLE
Weakest player condition

### ISSUE THREAD

**Issue by N69S** [RoganMurley/Ring-of-Worlds#8]
When playing against CPU, and "Hurt weakest player for 15" card comes into play and both the player and the CPU are at the same amount of life points, and regardless of who owns the card; the player takes the damage.

**Comment by RoganMurley** [comment]
Yes this shouldn't happen, it should either hurt the owner of the card or their opponent consistently. Thanks for the report!

**Comment by RoganMurley** [comment]
Hm from my testing the card always hurts both players, hurting the card's owner first. What do you expect?

**Comment by N69S** [comment]
I expected those kind of card to negate if both players had the same health. It would lead to some more intense games.

**Comment by RoganMurley** [comment]
Sounds reasonable, let's try it out! I've [pushed the change](https://github.com/RoganMurley/Ring-of-Worlds/commit/f58208d64af0cbc99e692dfd305f054234912fc2) and it'll be live within the day.
